---
version: '2.2'

services:
  openhab:
    image: "openhab/openhab:2.3.0"
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./addons:/openhab/addons"
      - "./config:/openhab/conf"
      - "./userdata:/openhab/userdata"
      - "./cont-init.d:/etc/cont-init.d"
    env_file: uidgid.env
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin -Dgnu.io.rxtx.SerialPorts=/dev/ttyAMA0:/dev/ttyS0:/dev/serial0:/dev/serial1"
      USER_ID: 1001
      GROUP_ID: 1001
    devices:
        - /dev/ttyAMA0
    networks:
      - home
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openhab.tls=true"
      - "traefik.http.routers.openhab.entrypoints=websecure"
      - "traefik.http.routers.openhab.middlewares=auth@file"
      - "traefik.http.routers.openhab.rule=Host(`openhab.home.alhome.uk`)"
      - "traefik.http.services.openhab.loadbalancer.server.port=8080"

  mosquitto:
    image: "eclipse-mosquitto:1.6.9"
    restart: always
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
    env_file: uidgid.env
    environment:
      USER_ID: 1001
      GROUP_ID: 1001
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - home

networks:
  home:
    external:
      name: home
